/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadgrupo28.Vistas;

import javax.swing.JOptionPane;
import universidadgrupo28.AccesoADatos.MateriaData;
import universidadgrupo28.Entidades.Materia;

/**
 *
 * @author myria
 */
public class FormularioMateria extends javax.swing.JInternalFrame {
private MateriaData md;

    /**
     * Creates new form FormularioMateria
     */
    public FormularioMateria() {
        md=new MateriaData();
        initComponents();
        jbNuevaMat.setEnabled(true);
        jbEliminarMat.setEnabled(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtCodigoMat = new javax.swing.JTextField();
        jtNombreMat = new javax.swing.JTextField();
        jtAnio = new javax.swing.JTextField();
        jrbEstado = new javax.swing.JRadioButton();
        jbNuevaMat = new javax.swing.JButton();
        jbEliminarMat = new javax.swing.JButton();
        jbGuardarMat = new javax.swing.JButton();
        jbSalirMateria = new javax.swing.JButton();
        jbBuscarMat = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Formulario de Materia");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Materia");

        jLabel2.setText("Codigo");

        jLabel3.setText("Nombre");

        jLabel4.setText("Año");

        jLabel5.setText("Estado");

        jtCodigoMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCodigoMatActionPerformed(evt);
            }
        });

        jtNombreMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreMatActionPerformed(evt);
            }
        });

        jtAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtAnioActionPerformed(evt);
            }
        });

        jrbEstado.setText("Activo");

        jbNuevaMat.setText("Nuevo");
        jbNuevaMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevaMatActionPerformed(evt);
            }
        });

        jbEliminarMat.setText("Eliminar");
        jbEliminarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarMatActionPerformed(evt);
            }
        });

        jbGuardarMat.setText("Guardar");
        jbGuardarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarMatActionPerformed(evt);
            }
        });

        jbSalirMateria.setText("Salir");
        jbSalirMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirMateriaActionPerformed(evt);
            }
        });

        jbBuscarMat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search_find_lupa_21889.png"))); // NOI18N
        jbBuscarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarMatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtNombreMat, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtCodigoMat, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jbBuscarMat))
                            .addComponent(jrbEstado))))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jbNuevaMat)
                .addGap(18, 18, 18)
                .addComponent(jbEliminarMat)
                .addGap(18, 18, 18)
                .addComponent(jbGuardarMat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSalirMateria)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtCodigoMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jbBuscarMat)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtNombreMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jrbEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNuevaMat)
                    .addComponent(jbEliminarMat)
                    .addComponent(jbGuardarMat)
                    .addComponent(jbSalirMateria))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirMateriaActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirMateriaActionPerformed

    private void jtCodigoMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCodigoMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCodigoMatActionPerformed

    private void jtNombreMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNombreMatActionPerformed

    private void jtAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtAnioActionPerformed

    private void jbNuevaMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevaMatActionPerformed
        // TODO add your handling code here:
        activarCampos();
        limpiar();
        jtCodigoMat.requestFocus();
        jbEliminarMat.setEnabled(false);
        jbNuevaMat.setEnabled(true);
        jbGuardarMat.setEnabled(true);
        jtAnio.setEnabled(false);
        jtCodigoMat.setText("");
        

    }//GEN-LAST:event_jbNuevaMatActionPerformed

    private void jbBuscarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarMatActionPerformed
        // TODO add your handling code here:
        try{
                int cod=Integer.parseInt(jtCodigoMat.getText());
                Materia mate=md.buscarMateriaPorAnio(cod);
                if(mate!=null){
                    jtNombreMat.setText(mate.getNombre());
                    jtAnio.setToolTipText(title);
                    jrbEstado.setSelected(mate.isEstado());
            
                activarCampos();
                jbEliminarMat.setEnabled(true);
                }else{
                    limpiar();
                    desactivarCampos();
                    jbGuardarMat.setEnabled(false);
                   
                }       
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog (this, "Debe ingresar un numero");
            jtCodigoMat.requestFocus();
            limpiar();
            desactivarCampos();
            
        }

    }//GEN-LAST:event_jbBuscarMatActionPerformed

    private void jbGuardarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarMatActionPerformed
        // TODO add your handling code here:
        Materia mat=new Materia();
        try{
            int cod=Integer.parseInt(jtCodigoMat.getText());
            String nombre=jtNombreMat.getText();
            String anio=jtAnio.getToolTipText();
            boolean Estado=jrbEstado.isSelected();
            
            mat.setIdMateria(WIDTH);
            mat.setNombre(nombre);
            mat.setEstado(Estado);
            
            md.guaradarMateria(mat);
            limpiar();
            desactivarCampos();
            jbNuevaMat.setEnabled(true);
            jbGuardarMat.setEnabled(true);
            
        }catch(NumberFormatException a){
            JOptionPane.showMessageDialog (this, "No puede dejar campos vacios");
                        
        }
        
    }//GEN-LAST:event_jbGuardarMatActionPerformed

    private void jbEliminarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarMatActionPerformed
        // TODO add your handling code here:
        
        try {
            
            int cod=Integer.parseInt(jtCodigoMat.getText());
            Materia mate=md.buscarMateriaPorAnio(cod);
            if(mate !=null){
                
                jtCodigoMat.setText(String.valueOf(mate.getAnioMateria()));
                jtNombreMat.setText(mate.getNombre());
                jtAnio.setToolTipText(title);
                jrbEstado.setSelected(mate.isEstado());
                
                limpiar();
                desactivarCampos();
                
                md.elimnarMateria(cod);
            }else{
                JOptionPane.showMessageDialog (null, "No esa materia");
            
            }
        }catch(NumberFormatException e) {
            JOptionPane.showMessageDialog (this, "Codigo invalido");
            limpiar();
            desactivarCampos();
            jbNuevaMat.setEnabled(true);
            }
        
        

    }//GEN-LAST:event_jbEliminarMatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbBuscarMat;
    private javax.swing.JButton jbEliminarMat;
    private javax.swing.JButton jbGuardarMat;
    private javax.swing.JButton jbNuevaMat;
    private javax.swing.JButton jbSalirMateria;
    private javax.swing.JRadioButton jrbEstado;
    private javax.swing.JTextField jtAnio;
    private javax.swing.JTextField jtCodigoMat;
    private javax.swing.JTextField jtNombreMat;
    // End of variables declaration//GEN-END:variables

    private void activarCampos() {
        jtCodigoMat.setEnabled(true);
        jtNombreMat.setEnabled(true);
        jtAnio.setEnabled(true);
        jrbEstado.setEnabled(true);
        jbNuevaMat.setEnabled(true);
        jbEliminarMat.setEnabled(true);
        jbGuardarMat.setEnabled(true);
    }

    private void limpiar() {
        jtCodigoMat.setToolTipText(title);
        jtNombreMat.setText("");
        jtAnio.setText("");
        jrbEstado.setSelected(false);
    }

    private void desactivarCampos() {
        jtCodigoMat.setEnabled(false);
        jtNombreMat.setEnabled(false);
        jtAnio.setEnabled(false);
        jrbEstado.setEnabled(false);
        jbNuevaMat.setEnabled(false);  
        jbEliminarMat.setEnabled(false);
        jbGuardarMat.setEnabled(false);        
        
    }    
}

