
package universidadgrupo28.Vistas;

/**
 *
 * @author Gustavo
 */
public class FormularioCerrar extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioCerrar
     */
    public FormularioCerrar() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jbCerrarP = new javax.swing.JButton();

        jbCerrarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universidadgrupo28/Imagenes/off_logout_17916.png"))); // NOI18N
        jbCerrarP.setText("Cerrar Programa");
        jbCerrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarPActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jbCerrarP, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jbCerrarP)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbCerrarP, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCerrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarPActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbCerrarPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JDesktopPane jDesktopPane1;
    javax.swing.JButton jbCerrarP;
    // End of variables declaration//GEN-END:variables

}
