
package universidadgrupo28.Vistas;

import javax.swing.JOptionPane;
import universidadgrupo28.AccesoADatos.MateriaData;
import universidadgrupo28.Entidades.Materia;


public class FormularioMateria extends javax.swing.JInternalFrame {
private MateriaData md;

    public FormularioMateria() {
        initComponents();
        
          md=new MateriaData();
       
        desactivarCampos();
        jbGuardar.setEnabled(false);
        jbEliminar.setEnabled(false);
         jbModificar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtCodigo = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtAnio = new javax.swing.JTextField();
        jrbEstado = new javax.swing.JRadioButton();
        jbBuscar = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();

        setTitle("Formulario de Materia");

        jLabel1.setFont(new java.awt.Font("Californian FB", 1, 20)); // NOI18N
        jLabel1.setText("Materia");

        jLabel2.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel2.setText("Codigo");

        jLabel3.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel4.setText("Año");

        jLabel5.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel5.setText("Estado");

        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universidadgrupo28/Imagenes/search_find_lupa_21889.png"))); // NOI18N
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universidadgrupo28/Imagenes/book_1427.png"))); // NOI18N
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universidadgrupo28/Imagenes/trash_empty_14645.png"))); // NOI18N
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universidadgrupo28/Imagenes/savedisk_floppydisk_guardar_1543.png"))); // NOI18N
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universidadgrupo28/Imagenes/cancellationbutton_exitneartheaction_botondecancelacion_salida_6335.png"))); // NOI18N
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universidadgrupo28/Imagenes/edit_pencil_6320.png"))); // NOI18N
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jbBuscar))
                    .addComponent(jtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbEstado))
                .addGap(0, 134, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel1)
                .addGap(136, 295, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jbNuevo)
                .addGap(38, 38, 38)
                .addComponent(jbEliminar)
                .addGap(30, 30, 30)
                .addComponent(jbGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbModificar)
                .addGap(28, 28, 28)
                .addComponent(jbSalir)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jbBuscar)))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(65, 65, 65)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbEstado)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        
        try{
                int cod=Integer.parseInt(jtCodigo.getText());
                Materia mate=md.buscarMateria(cod);
             
                String nombre = jtNombre.getText();
                
                if(mate!=null){
               
                jtNombre.setText(mate.getNombre());
                int anio = mate.getAnioMateria();
                jtAnio.setText(String.valueOf(anio));

                jrbEstado.setSelected(mate.isEstado());
       
             activarCampos();
             jbEliminar.setEnabled(true);
              jbGuardar.setEnabled(false);
              jbModificar.setEnabled(true);
                }else{
                    limpiar();
                    activarCampos();
                   desactivarCampos();
            
                }       
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog (null, "Debe ingresar un numero");
            jtCodigo.requestFocus();
            limpiar();
            desactivarCampos();
            
        } 
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        // TODO add your handling code here:
        
        activarCampos();
        limpiar();
        jtCodigo.requestFocus();
        jbEliminar.setEnabled(false);
        jbNuevo.setEnabled(false);
        jbGuardar.setEnabled(true);
        jtCodigo.setText("");
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        
         try {
            
            int cod=Integer.parseInt(jtCodigo.getText());
            Materia mate=md.buscarMateria(cod);
            if(mate !=null){
                
                jtCodigo.setText(String.valueOf(mate.getAnioMateria()));
                jtNombre.setText(mate.getNombre());
                jtAnio.setToolTipText(title);
                jrbEstado.setSelected(mate.isEstado());
                
              
            md.elimnarMateria(cod);
            
                limpiar();
                desactivarCampos();
                jbEliminar.setEnabled(false);
                jbModificar.setEnabled(false);
            
            }
        }catch(NumberFormatException e) {
            JOptionPane.showMessageDialog (this, "Codigo invalido");
            limpiar();
            desactivarCampos();
            jbNuevo.setEnabled(true);
            }
        
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
        
         Materia mat=new Materia();
        try{
            
            int cod=Integer.parseInt(jtCodigo.getText());
            String nombre=jtNombre.getText();
            int anio=Integer.parseInt(jtAnio.getText());
            boolean estado=jrbEstado.isSelected();
            
            mat.setIdMateria(cod);
            mat.setNombre(nombre);
            mat.setEstado(estado);
            mat.setAnioMateria(anio);
            
            md.guaradarMateria(mat);
          
            limpiar();
            desactivarCampos();
            jbNuevo.setEnabled(true);
            jbGuardar.setEnabled(false);
            jbModificar.setEnabled(false);
            
        }catch(NumberFormatException a){
            JOptionPane.showMessageDialog (this, "No puede dejar campos vacios");
                        
        }
        
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        
         dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        // TODO add your handling code here:
        
        
        try{
            
            int cod=Integer.parseInt(jtCodigo.getText());
            String nombre=jtNombre.getText();
            int anio=Integer.parseInt(jtAnio.getText());
            boolean estado=jrbEstado.isSelected();
            
            Materia mat= md.buscarMateria(cod);
            
            if(mat == null){
                
               mat = new Materia();
                mat.setIdMateria(cod);     
            }
               
               mat.setNombre(nombre);
               mat.setEstado(estado);
               mat.setAnioMateria(anio);
               
            if(mat.getIdMateria() != 0){
              md.modificarMateria(mat);
            }
              limpiar();
              desactivarCampos();
              jbNuevo.setEnabled(true);
              jbGuardar.setEnabled(false);
              jbEliminar.setEnabled(false);
              jbModificar.setEnabled(false);
            
        }catch(NumberFormatException a){
            JOptionPane.showMessageDialog (this, "No puede dejar campos vacios");
                        
        }
    }//GEN-LAST:event_jbModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JRadioButton jrbEstado;
    private javax.swing.JTextField jtAnio;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables

private void desactivarCampos() {
        //jtNombre.setEnabled(false);
        jtAnio.setEnabled(false);
        jrbEstado.setEnabled(false);
        
    } 
    
     private void activarCampos() {
        jtCodigo.setEnabled(true);
        jtNombre.setEnabled(true);
        jtAnio.setEnabled(true);
        jrbEstado.setEnabled(true);
    }

 
    private void limpiar() {
        jtCodigo.setText("");
        jtNombre.setText("");
        jtAnio.setText("");
        jrbEstado.setSelected(false);
    }


}
